modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="far_past"
version="1.1.0"
displayName="far past"
displayURL="https://www.curseforge.com/minecraft/mc-mods"
credits="java port by dinofan"
authors="dinofan"
description="far past"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.far_past]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.far_past]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.far_past]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration